name: On Repository A Push

on:
  repository_dispatch:
    types:
      - trigger-event

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository B
        uses: actions/checkout@v2

      - name: Run tests
        run: npx cypress run
